(global-set-key (kbd "C-c C-e") 'eval-defun)
(global-unset-key (kbd "M-l"))
(global-set-key (kbd "M-l") 'goto-line)
(defun goto-end-of-line (n)
  (interactive "nGoto end of line: ")
  (goto-char (point-min)) (forward-line (1- n))
  (move-end-of-line nil))
(global-unset-key (kbd "M-o"))
(global-set-key (kbd "M-o") 'goto-end-of-line)
(provide 'tom-bindings)
